spring.application.name=skilLink

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/skillink
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- GitHub ---
spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_CLIENT_SECRET
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# --- Google ---
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# --- Apple ---
spring.security.oauth2.client.registration.apple.client-id=YOUR_APPLE_CLIENT_ID
spring.security.oauth2.client.registration.apple.client-secret=YOUR_APPLE_CLIENT_SECRET
spring.security.oauth2.client.registration.apple.scope=email,name
spring.security.oauth2.client.registration.apple.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.apple.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.apple.provider=apple

spring.security.oauth2.client.provider.apple.authorization-uri=https://appleid.apple.com/auth/authorize
spring.security.oauth2.client.provider.apple.token-uri=https://appleid.apple.com/auth/token
spring.security.oauth2.client.provider.apple.user-info-uri=https://appleid.apple.com/auth/userinfo
spring.security.oauth2.client.provider.apple.user-name-attribute=sub



app.jwt.secret=6fH8qG3vX1kB9pL0sR4eT2wY7zJ5vU8xN1aC6dP3fR0hT2qM
app.jwt.issuer=skillink
app.jwt.access-token-minutes=60
app.jwt.refresh-token-days=7

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/spring-boot-application.log

